apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "evolution.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ include "evolution.name" . }}-secrets
data:
  {{- range $key, $value := .Values.env}}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
