# pgAdmin Ingress Configuration for Traefik behind Cloudflare
# Use this file to deploy pgAdmin with proper ingress settings for Traefik when Cloudflare handles HTTPS
# Example: helm upgrade pgadmin ./charts/pgadmin -f ./charts/pgadmin/values.ingress.yaml

# Enable ingress
ingress:
  enabled: true
  className: "traefik"
  createMiddleware: true
  annotations:
    # The chart will set the router middleware automatically
    # when createMiddleware is true
    # Use web entrypoint (port 80) since Cloudflare handles HTTPS
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
    
  hosts:
    - host: pgadmin.saas.chatwoot.app.br
      paths:
        - path: /
          pathType: ImplementationSpecific
  # No TLS section needed - Cloudflare handles HTTPS termination

# pgAdmin Configuration for Cloudflare + Traefik
pgadmin:
  # Update with your actual credentials
  defaultEmail: "admin@chatwoot.app.br"
  defaultPassword: "YourSecurePassword123!"
  
  # Disable TLS inside container since Cloudflare handles it
  enableTLS: false
  
  # Gunicorn settings - fix timeout issue
  gunicorn:
    accessLogFile: "-"
    limitRequestLine: 8190
    threads: 25
    timeout: 120
  
  # Configuration for reverse proxy setup
  config:
    # Important: Tell pgAdmin it's behind HTTPS reverse proxy (Cloudflare)
    ENHANCED_COOKIE_PROTECTION: True
    CONSOLE_LOG_LEVEL: 20  # INFO level
    SESSION_EXPIRATION_TIME: 8  # Hours
    
    # Configure proxy settings for Cloudflare + Traefik
    # Trust two values because requests pass through
    # Cloudflare and Traefik
    PROXY_X_FOR_COUNT: 2
    PROXY_X_PROTO_COUNT: 2
    PROXY_X_HOST_COUNT: 2
    PROXY_X_PORT_COUNT: 2
    
    # Secure cookie settings for HTTPS (handled by Cloudflare)
    SESSION_COOKIE_SECURE: True
    SESSION_COOKIE_HTTPONLY: True
    SESSION_COOKIE_SAMESITE: "'Lax'"
