{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    accessControlAllowOriginList:
    {{- range .Values.ingress.hosts }}
      - https://{{ .host }}
    {{- end }}
    {{- if .Values.ingress.cors }}
    {{- range .Values.ingress.cors }}
      - {{ . }}
    {{- end }}
    {{- end }}
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - "*"
    accessControlMaxAge: 100
    addVaryHeader: true
{{- end }}
