apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.defaultEmail | b64enc | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.defaultPassword | b64enc | quote }}
